SELECT
    N.NU_CUI,
    N.DE_PRE_NOMBRES,
    N.DE_PRIMER_APELLIDO,
    N.DE_SEGUNDO_APELLIDO,
    N.FE_NACIMIENTO,
    N.IM_NACIMIENTOS_REV AS IMAGEN_REVERSO,
    IM_NACIMIENTOS as IMAGEN_ANVERSO
FROM
    IDORRCC.RCTM_NACIMIENTOS N
WHERE
    N.CO_ESTADO_ACTA_NACIMIENTO = '1'
    AND