SELECT
    N.NU_CUI,
    N.DE_PRE_NOMBRES,
    N.DE_PRIMER_APELLIDO,
    N.DE_SEGUNDO_APELLIDO,
    N.FE_NACIMIENTO,
    CASE
        WHEN N.IM_NACIMIENTOS IS NOT NULL THEN N.IM_NACIMIENTOS
        ELSE R.IM_ACTA
    END AS IMAGEN_ANVERSO,
    CASE
        WHEN N.IM_NACIMIENTOS_REV IS NOT NULL THEN N.IM_NACIMIENTOS_REV
        ELSE I.IM_ACTA
    END AS IMAGEN_REVERSO
FROM
    IDORRCC.RCTM_NACIMIENTOS N
LEFT JOIN IDORRCC.RCTM_ESCANEO R
    ON R.NU_ACTA = N.NU_ACTA_NACIMIENTO
    AND R.CO_TIPO_ACTA = '01'
    AND R.CO_LADO_ACTA = 'A'
    AND R.IM_ACTA IS NOT NULL
LEFT JOIN IDORRCC.RCTM_ESCANEO I
    ON I.NU_ACTA = N.NU_ACTA_NACIMIENTO
    AND I.CO_TIPO_ACTA = '01'
    AND I.CO_LADO_ACTA = 'B'
    AND I.IM_ACTA IS NOT NULL
WHERE
    N.CO_ESTADO_ACTA_NACIMIENTO = '1'
    AND N.PRIMER_APELLIDO = p_primer_apellido,
    AND N.DE_SEGUNDO_APELLIDO = p_segundo_apellido,
    AND N.DE_PRE_NOMBRES = p_pre_nombres,
    AND N.FE_NACIMIENTO = p_fecha_nacimiento,
    AND N.CO_NACIDO_NATURAL_CONT = p_nac_nat_cont,
    AND N.CO_NACIDO_NATURAL_PAIS = p_nac_nat_pais,
    AND N.CO_CO_NACIDO_NATURAL_DPTO = p_nac_nat_dpto,
    AND N.CO_CO_NACIDO_NATURAL_PROV = p_nac_nat_prov,
    AND N.CO_CO_NACIDO_NATURAL_DIST = p_nac_nat_dist,
    AND N.CO_CO_NACIDO_NATURAL_LOCA = p_nac_nat_loca;
