SELECT
    N.NU_CUI,
    N.DE_PRE_NOMBRES,
    N.DE_PRIMER_APELLIDO,
    N.DE_SEGUNDO_APELLIDO,
    N.FE_NACIMIENTO,
    CASE
        WHEN N.IM_NACIMIENTOS IS NOT NULL THEN N.IM_NACIMIENTOS
        ELSE R.IM_ACTA
    END AS IMAGEN_ANVERSO,
    CASE
        WHEN N.IM_NACIMIENTOS_REV IS NOT NULL THEN N.IM_NACIMIENTOS_REV
        ELSE I.IM_ACTA
    END AS IMAGEN_REVERSO
FROM
    IDORRCC.RCTM_NACIMIENTOS N
LEFT JOIN IDORRCC.RCTM_ESCANEO R
    ON R.NU_ACTA = N.NU_ACTA_NACIMIENTO
    AND R.CO_TIPO_ACTA = '01'
    AND R.CO_LADO_ACTA = 'A'
    AND R.IM_ACTA IS NOT NULL
LEFT JOIN IDORRCC.RCTM_ESCANEO I
    ON I.NU_ACTA = N.NU_ACTA_NACIMIENTO
    AND I.CO_TIPO_ACTA = '01'
    AND I.CO_LADO_ACTA = 'B'
    AND I.IM_ACTA IS NOT NULL
WHERE
    N.CO_ESTADO_ACTA_NACIMIENTO = '1'
    AND N.NU_CUI = p_nu_cui;