-- Tabla de auditoría de peticiones al WS de actas.
-- Ejecutar conectado como IDORRCC o tras ALTER SESSION SET CURRENT_SCHEMA = IDORRCC;
-- En producción, opcionalmente especificar TABLESPACE (p. ej. TBL_...) según estándar DBA.

ALTER SESSION SET CURRENT_SCHEMA = IDORRCC;

CREATE TABLE IDORRCC.RCTL_ACTAS_LOGS (
    FE_LOG                 DATE DEFAULT SYSDATE NOT NULL,
    DE_MENSAJE_LOG         VARCHAR2(400) NOT NULL,
    ID_LOG                 VARCHAR2(36),
    CO_DNI_SOLICITANTE     VARCHAR2(8),
    CO_DNI_SOLICITADO      VARCHAR2(8),
    DE_PERFIL_SOLICITADO   VARCHAR2(50),
    IP_DIRECCION_ORIGEN    VARCHAR2(45),
    ES_RESULTADO           VARCHAR2(10),
    DE_MENSAJE_ERROR       VARCHAR2(400)
);

COMMENT ON TABLE IDORRCC.RCTL_ACTAS_LOGS IS 'Tabla de logs de peticiones al servicio de actas DNID';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.FE_LOG IS 'Fecha y hora del registro de log';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.DE_MENSAJE_LOG IS 'Mensaje principal de auditoria generado por la aplicacion';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.ID_LOG IS 'Identificador unico del evento de log (UUID)';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.CO_DNI_SOLICITANTE IS 'DNI del usuario o sistema que realiza la solicitud';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.CO_DNI_SOLICITADO IS 'DNI consultado en la operacion';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.DE_PERFIL_SOLICITADO IS 'Profile solicitado (ej. ACTA_NACIMIENTO, ACTA_MATRIMONIO)';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.IP_DIRECCION_ORIGEN IS 'Direccion IP de origen de la peticion';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.ES_RESULTADO IS 'Resultado de la operacion: OK o ERROR';
COMMENT ON COLUMN IDORRCC.RCTL_ACTAS_LOGS.DE_MENSAJE_ERROR IS 'Mensaje de error legible; NULL en caso exitoso';

CREATE INDEX IDXBT_RCTL_ACTAS_LOGS_01 ON IDORRCC.RCTL_ACTAS_LOGS (FE_LOG);
