SELECT
  J.NU_ACTA_MATRIMONIO,
  J.DE_MATERIA,
  J.DE_TRANSCRIPCION
FROM IDORRCC.RCTV_ACTA_RECTIFICACION_MAT J,
     IDORRCC.RCTR_MATRIMONIOS_PROCESOS P
WHERE
  J.CO_PROCESO_MATRIMONIO=P.CO_PROCESO_MATRIMONIO
  AND NVL(J.IN_LINEA,' ')='1'
  AND J.ES_REGISTRO='1'
  AND NVL(P.IN_IMPRIME_AM,' ')='1'