SELECT
  J.NU_ACTA_NACIMIENTO,
  J.DE_MATERIA,
  J.DE_TRANSCRIPCION
FROM IDORRCC.RCTV_ACTA_RECTIFICACION_NAC J,
     IDORRCC.RCTR_NACIMIENTOS_PROCESOS P
WHERE
  J.CO_PROCESO_NACIMIENTO=P.CO_PROCESO_NACIMIENTO
  AND NVL(J.IN_LINEA,' ')='1'
  AND J.ES_REGISTRO='1'
  AND NVL(P.IN_IMPRIME_AM,' ')='1'
  AND J.NU_ACTA_NACIMIENTO=3000491955